-- Import facilities 20 & 28 from Facinect dump (PostgreSQL)
INSERT INTO facilities (id, name, slug, status) VALUES (20, 'strolllabstesting', 'strolllabstesting', 'active') ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, status=EXCLUDED.status;
INSERT INTO facilities (id, name, slug, status) VALUES (28, 'Drops N Smashes', 'drops-n-smashes', 'active') ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, status=EXCLUDED.status;
SELECT setval(pg_get_serial_sequence('facilities','id'), GREATEST((SELECT MAX(id) FROM facilities), 1));
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('rajabharathi453@gmail.com', '917708054914', '$2y$10$e.JhNEo/6.bgNnsvJ4otbeOoRoTIRmI17vumMlI/ZU5I7Rcc0bFDO', 'Developer', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 20, 'admin', '["dashboard","bookings","view_bookings","students","members","payments","tournaments","enquiry","offers","administration"]'::jsonb, 'active' FROM users WHERE email = 'rajabharathi453@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 28, 'admin', '["dashboard","bookings","view_bookings","students","members","payments","tournaments","enquiry","offers","administration"]'::jsonb, 'active' FROM users WHERE email = 'rajabharathi453@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('sama.a.p.49@gmail.com', '917550193398', NULL, 'Monesh', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 20, 'sub_admin', '["students"]'::jsonb, 'active' FROM users WHERE email = 'sama.a.p.49@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 28, 'sub_admin', '["students"]'::jsonb, 'active' FROM users WHERE email = 'sama.a.p.49@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('bal.jop@gmail.com', '919445812511', '$2y$10$JM.G08MM2d0JGsk0jfr2Uu4YYlaXuTvUG1YuImLJKDJ3X3asBTbpK', 'Balaji', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 28, 'coach', '["students","tournaments"]'::jsonb, 'active' FROM users WHERE email = 'bal.jop@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 20, 'coach', '["students","tournaments"]'::jsonb, 'active' FROM users WHERE email = 'bal.jop@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('gopilin18@gmail.com', '919791687924', NULL, 'Gopi', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 28, 'coach', NULL, 'active' FROM users WHERE email = 'gopilin18@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('bhavadharini568@gmail.com', '919445563654', NULL, 'Bhavadharini', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 28, 'coach', '["students"]'::jsonb, 'active' FROM users WHERE email = 'bhavadharini568@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 20, 'coach', '["students"]'::jsonb, 'active' FROM users WHERE email = 'bhavadharini568@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('strollbyktest@gmail.com', NULL, NULL, 'TestUser', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 20, 'headcoach', NULL, 'active' FROM users WHERE email = 'strollbyktest@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('moneshraju@gmail.com', NULL, NULL, 'Monesh', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 28, 'admin', '["dashboard","bookings","view_bookings","students","members","payments","tournaments","enquiry","offers","administration"]'::jsonb, 'active' FROM users WHERE email = 'moneshraju@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 20, 'admin', '["dashboard","bookings","view_bookings","students","members","payments","tournaments","enquiry","offers","administration"]'::jsonb, 'active' FROM users WHERE email = 'moneshraju@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('dhanaseelanb@augmalabs.com', '9179598054914', NULL, 'Dhanaseelan', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 20, 'admin', NULL, 'active' FROM users WHERE email = 'dhanaseelanb@augmalabs.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('bdhanaseelan18@gmail.com', '917305694860', NULL, 'Dhanaseelan', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 20, 'admin', NULL, 'active' FROM users WHERE email = 'bdhanaseelan18@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('bdhanaseelan13@gmail.com', '917305694862', NULL, 'Dhanaseelan B', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 20, 'admin', NULL, 'active' FROM users WHERE email = 'bdhanaseelan13@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('strollbyk@gmail.com', '917010712515', NULL, 'Self_coach', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 28, 'coach', NULL, 'active' FROM users WHERE email = 'strollbyk@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('iagqmfo@outlook.com', '917464365880', NULL, 'Priya Raj', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 20, 'admin', NULL, 'active' FROM users WHERE email = 'iagqmfo@outlook.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('dhanaseelanb@augmalbs.com', NULL, NULL, 'Dhanaseelan b', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 20, 'coach', NULL, 'active' FROM users WHERE email = 'dhanaseelanb@augmalbs.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('tsfvavd@outlook.com', '917904615227', NULL, 'Arjun Singh', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 20, 'admin', NULL, 'active' FROM users WHERE email = 'tsfvavd@outlook.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('basamadh97@gmail.com', '918838226071', NULL, 'Balu', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 28, 'admin', '["dashboard","bookings","view_bookings","students","members","tournaments","enquiry"]'::jsonb, 'active' FROM users WHERE email = 'basamadh97@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('jayashreekr98@gmail.com', NULL, NULL, 'Monesh', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 28, 'coach', '["dashboard","bookings","view_bookings","students","members","payments","tournaments","enquiry","offers","administration"]'::jsonb, 'active' FROM users WHERE email = 'jayashreekr98@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 20, 'coach', '["dashboard","bookings","view_bookings","students","members","payments","tournaments","enquiry","offers","administration"]'::jsonb, 'active' FROM users WHERE email = 'jayashreekr98@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
INSERT INTO users (email, phone_e164, password_hash, full_name, status) VALUES ('bal.job@gmail.com', NULL, NULL, 'Balaji', 'active') ON CONFLICT (email) DO UPDATE SET full_name=EXCLUDED.full_name, password_hash=COALESCE(EXCLUDED.password_hash, users.password_hash), status='active';
INSERT INTO user_facility_memberships (user_id, facility_id, role, page_access, status) SELECT id, 28, 'sub_admin', '["dashboard","bookings","view_bookings","students","members","tournaments","enquiry"]'::jsonb, 'active' FROM users WHERE email = 'bal.job@gmail.com' ON CONFLICT (user_id, facility_id) DO UPDATE SET role=EXCLUDED.role, page_access=EXCLUDED.page_access, status='active';
SELECT 'facilities' AS t, COUNT(*)::text AS n FROM facilities WHERE id IN (20,28) UNION ALL SELECT 'memberships_20_28', COUNT(*)::text FROM user_facility_memberships WHERE facility_id IN (20,28);
-- Facility sports + Hostinger sports_categories ids (PHP get_slots sportId)
ALTER TABLE facility_sports ADD COLUMN IF NOT EXISTS catalog_sport_id BIGINT NULL;
INSERT INTO facility_sports (facility_id, name, sort_order, status, catalog_sport_id) VALUES
  (20, 'Badminton', 0, 'active', 1),
  (20, 'Tennis', 1, 'active', 2),
  (20, 'Volleyball', 2, 'active', 8),
  (20, 'Bowling', 3, 'active', 17),
  (28, 'Badminton', 0, 'active', 1)
ON CONFLICT (facility_id, name) DO UPDATE SET
  status = 'active',
  sort_order = EXCLUDED.sort_order,
  catalog_sport_id = EXCLUDED.catalog_sport_id,
  updated_at = NOW();
